swagger: "2.0"
info:
  description: "Courses for Reserves returns a netid's courses that they are enrolled in and has reserves "
  version: "1.0.0"
  title: "Reserves"
  contact:
    email: "jhartzle@nd.edu"
host: "reserves.library.edu"
basePath: "/api"
schemes:
- "https"
paths:
  /courses_with_reserves/{netid}:
    get:
      summary: "Gets a user's netid"
      description: "Gets a user's netid"
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "path"
        name: "netid"
        type: string
        description: "The user's netid to return"
        required: true
      - in: "url"
        name: "user_email"
        type: string
        description: "The login email"
        required: true
      - in: "url"
        name: "user_token"
        type: string
        description: "The token to get the user in"
        required: true
      responses:
        200:
          description: "successful operation"
        401:
          description: "Unauthorized"
        404:
          description: "Invalid netid"
        500:
          description: "System Errors"
