##########################################
# Shared settings
##########################################

mysql_settings: &mysql_settings
  adapter: mysql2
  pool:    5
  encoding: utf8
  reconnect: false
  timeout: 5000
  username: <%= Rails.application.secrets.database["username"] %>
  password: <%= Rails.application.secrets.database["password"] %>
  host: <%= Rails.application.secrets.database["host"] %>
  database: <%= Rails.application.secrets.database["database"] %>

open_reserves_mysql_settings: &open_reserves_mysql_settings
  adapter: mysql2
  pool:    5
  encoding: utf8
  reconnect: false
  timeout: 5000
  username: <%= Rails.application.secrets.open_reserves["username"] %>
  password: <%= Rails.application.secrets.open_reserves["password"] %>
  host:     <%= Rails.application.secrets.open_reserves["host"] %>
  database: <%= Rails.application.secrets.open_reserves["database"] %>

##########################################
# Environments
##########################################

development:
  <<: *mysql_settings

test: &test
  <<: *mysql_settings

pre_production:
  <<: *mysql_settings

production:
  <<: *mysql_settings


open_reserves_development:
  <<: *open_reserves_mysql_settings

open_reserves_test:
  <<: *open_reserves_mysql_settings

open_reserves_pprd:
  <<: *open_reserves_mysql_settings

open_reserves_prod:
  <<: *open_reserves_mysql_settings
