# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  sakai:
    admin_username:
    admin_password:
  leganto:
    secret:
    consumer:
  okta:
    auth_server_id:
    client_id:
    client_secret:
    base_auth_url:
    redirect_url:
    logout_url:

development:
  <<: *defaults
  secret_key_base: acb4aa8ad61aa0d94b6830010b6a2da9ea4f1b6989c2828af943008c54bda1eafb03c81b54414a899122708369c4619463853b89f86fe2ecfbf03be086a9a774
  api_url: https://apipprd.library.nd.edu
  api_token: SCSGYmwqLqSyBTmxCQgM
  database:
    database: reserves_development
    username: root
    password:
    host:     localhost

test:
  <<: *defaults
  secret_key_base: 5f79cb5f5caa03cbe08921abb930021fd57bd4b16c18b8884a4838060de3a218d9e6b0926de408cc16932e65d10c1bb71ad568f9d3b3b4d495cff6db46d03223
  api_url:
  api_token:
  database:
    database: reserves_test
    username: root
    password:
    host:     localhost

prep:
  <<: *defaults
  secret_key_base:
  api_url:
  api_token:
  database:
    database:
    username:
    password:
    host:
  sentry:
    dsn:

production:
  <<: *defaults
  secret_key_base:
  api_url:
  api_token:
  database:
    database:
    username:
    password:
    host:
  sentry:
    dsn:
  okta:
    auth_server_id:
    client_id:
    client_secret:
    base_auth_url:
    redirect_url:
    logout_url:
