name: Ruby CI

on:
  push:
    branches-ignore: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install proper bundler gem
        run: gem install bundler -v 1.17.3
      - name: Install Ruby gems
        run: bundle install
    # Start the local mysql service
      - name: Start mysql
        run: sudo systemctl start mysql.service
    # Put the Database and Secrets files into place. We use the files with the ".actions" extension to avoid confusion or development impact
      - name: Copy config files
        run: |
          cp config/database.yml.actions config/database.yml
          cp config/secrets.yml.actions config/secrets.yml
      - name: Run rake tasks
        env:
          MYSQL_ROOT_PASSWORD: root
        run: bundle exec rspec